[versions]
gradle = "9.0.0"
kotlin = "2.3.0"
mockito = "5.2.0"
kotlinScriptUtil = "1.8.22"
junit = "4.13.2"
mockitoKotlin = "6.2.1"
mockk = "1.14.9"
assertjCore = "3.27.6"
hamcrest = "3.0"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-script-util = { module = "org.jetbrains.kotlin:kotlin-script-util", version.ref = "kotlinScriptUtil" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCore" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }

[plugins]
application = { id = "application" }
kotlin = { id = "kotlin" }

